"""
Hybrid Memory Manager for Agentic AI Travel Planner

Stores memory in three layers:
1. Redis -> short-term/session memory
2. MongoDB -> long-term structured memory
3. ChromaDB -> semantic/vector memory

This file keeps the same main methods as the old memory_manager.py:
- add_memory()
- get_memory()
- clear()

Environment variables supported:
REDIS_URL=mongodb style not needed, example: redis://localhost:6379/0
MONGO_URI=mongodb://localhost:27017
MONGO_DB_NAME=travel_agent
MONGO_COLLECTION_NAME=agent_memory
CHROMA_PERSIST_DIR=./chroma_memory
CHROMA_COLLECTION_NAME=travel_agent_memory
"""

from __future__ import annotations
import json
import os
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


class HybridMemoryManager:
    def __init__(
        self,
        session_id: str = "default_session",
        redis_url: Optional[str] = None,
        mongo_uri: Optional[str] = None,
        mongo_db_name: Optional[str] = None,
        mongo_collection_name: Optional[str] = None,
        chroma_persist_dir: Optional[str] = None,
        chroma_collection_name: Optional[str] = None,
        redis_ttl_seconds: int = 60 * 60 * 24,
    ):
        self.session_id = session_id
        self.redis_url = redis_url or os.getenv("REDIS_URL", "redis://localhost:6379/0")
        self.mongo_uri = mongo_uri or os.getenv("MONGO_URI", "mongodb://localhost:27017")
        self.mongo_db_name = mongo_db_name or os.getenv("MONGO_DB_NAME", "travel_agent")
        self.mongo_collection_name = mongo_collection_name or os.getenv(
            "MONGO_COLLECTION_NAME", "agent_memory"
        )
        self.chroma_persist_dir = chroma_persist_dir or os.getenv(
            "CHROMA_PERSIST_DIR", "./chroma_memory"
        )
        self.chroma_collection_name = chroma_collection_name or os.getenv(
            "CHROMA_COLLECTION_NAME", "travel_agent_memory"
        )
        self.redis_ttl_seconds = redis_ttl_seconds

        self.redis_client = None
        self.mongo_collection = None
        self.chroma_collection = None

        self._connect_redis()
        # self._connect_mongo()
        self._connect_chroma()

    # -----------------------------
    # Connections
    # -----------------------------

    def _connect_redis(self) -> None:
        try:
            import redis

            self.redis_client = redis.from_url(self.redis_url, decode_responses=True)
            self.redis_client.ping()
        except Exception:
            self.redis_client = None

    def _connect_mongo(self) -> None:
        try:
            from pymongo import MongoClient

            mongo_client = MongoClient(self.mongo_uri, serverSelectionTimeoutMS=3000)
            mongo_client.admin.command("ping")
            db = mongo_client[self.mongo_db_name]
            self.mongo_collection = db[self.mongo_collection_name]
        except Exception:
            self.mongo_collection = None

    def _connect_chroma(self) -> None:
        try:
            import chromadb

            chroma_client = chromadb.PersistentClient(path=self.chroma_persist_dir)
            self.chroma_collection = chroma_client.get_or_create_collection(
                name=self.chroma_collection_name
            )
        except Exception:
            self.chroma_collection = None

    # -----------------------------
    # Helpers
    # -----------------------------

    def _redis_key(self) -> str:
        return f"travel_agent:memory:{self.session_id}"

    def _now(self) -> str:
        return datetime.now(timezone.utc).isoformat()

    def _safe_json(self, data: Any) -> str:
        try:
            return json.dumps(data, default=str)
        except Exception:
            return json.dumps({"value": str(data)})

    def _memory_text(self, record: Dict[str, Any]) -> str:
        return self._safe_json(record)

    # -----------------------------
    # Main API - compatible with old memory_manager.py
    # -----------------------------

    def add_memory(
        self,
        tool_name: str,
        observation: Any,
        user_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Save memory in Redis, MongoDB, and ChromaDB.

        Args:
            tool_name: Agent/tool name, for example activity_agent.
            observation: Result or error generated by agent/tool.
            user_id: Optional user identifier.
            metadata: Optional extra metadata.

        Returns:
            The memory record created.
        """

        memory_id = str(uuid.uuid4())
        record = {
            "id": memory_id,
            "session_id": self.session_id,
            "user_id": user_id,
            "tool": tool_name,
            "observation": observation,
            "metadata": metadata or {},
            "created_at": self._now(),
        }

        self._save_to_redis(record)
        self._save_to_mongo(record)
        self._save_to_vector_db(record)

        return record

    def get_memory(self, limit: int = 20) -> List[Dict[str, Any]]:
        """
        Get recent memory.
        Priority:
        1. Redis
        2. MongoDB
        3. Empty list
        """

        redis_memory = self._get_from_redis(limit=limit)
        if redis_memory:
            return redis_memory

        mongo_memory = self._get_from_mongo(limit=limit)
        if mongo_memory:
            return mongo_memory

        return []

    def search_memory(self, query: str, limit: int = 5) -> List[Dict[str, Any]]:
        """
        Semantic memory search using ChromaDB.
        Useful for finding similar past trips, preferences, or agent observations.
        """

        if self.chroma_collection is None:
            return []

        try:
            results = self.chroma_collection.query(
                query_texts=[query],
                n_results=limit,
            )

            documents = results.get("documents", [[]])[0]
            metadatas = results.get("metadatas", [[]])[0]
            ids = results.get("ids", [[]])[0]

            output = []
            for idx, document in enumerate(documents):
                output.append(
                    {
                        "id": ids[idx] if idx < len(ids) else None,
                        "document": document,
                        "metadata": metadatas[idx] if idx < len(metadatas) else {},
                    }
                )
            return output
        except Exception:
            return []

    def clear(self) -> None:
        """
        Clear current session memory from Redis.
        MongoDB and Vector DB are not deleted because they are long-term memory.
        """

        if self.redis_client is not None:
            try:
                self.redis_client.delete(self._redis_key())
            except Exception:
                pass

    def clear_all(self) -> None:
        """
        Clear current session from Redis and MongoDB.
        Use carefully.
        Vector DB entries are kept by default.
        """

        self.clear()

        if self.mongo_collection is not None:
            try:
                self.mongo_collection.delete_many({"session_id": self.session_id})
            except Exception:
                pass

    # -----------------------------
    # Redis Methods - Short-term memory
    # -----------------------------

    def _save_to_redis(self, record: Dict[str, Any]) -> None:
        if self.redis_client is None:
            return

        try:
            key = self._redis_key()
            self.redis_client.rpush(key, self._safe_json(record))
            self.redis_client.expire(key, self.redis_ttl_seconds)
        except Exception:
            pass

    def _get_from_redis(self, limit: int = 20) -> List[Dict[str, Any]]:
        if self.redis_client is None:
            return []

        try:
            key = self._redis_key()
            raw_items = self.redis_client.lrange(key, -limit, -1)
            return [json.loads(item) for item in raw_items]
        except Exception:
            return []

    # -----------------------------
    # MongoDB Methods - Long-term structured memory
    # -----------------------------

    def _save_to_mongo(self, record: Dict[str, Any]) -> None:
        if self.mongo_collection is None:
            return

        try:
            self.mongo_collection.insert_one(record.copy())
        except Exception:
            pass

    def _get_from_mongo(self, limit: int = 20) -> List[Dict[str, Any]]:
        if self.mongo_collection is None:
            return []

        try:
            cursor = (
                self.mongo_collection.find({"session_id": self.session_id}, {"_id": 0})
                .sort("created_at", -1)
                .limit(limit)
            )
            records = list(cursor)
            records.reverse()
            return records
        except Exception:
            return []

    # -----------------------------
    # ChromaDB Methods - Semantic memory
    # -----------------------------

    def _save_to_vector_db(self, record: Dict[str, Any]) -> None:
        if self.chroma_collection is None:
            return

        try:
            text = self._memory_text(record)
            metadata = {
                "session_id": str(record.get("session_id")),
                "user_id": str(record.get("user_id")),
                "tool": str(record.get("tool")),
                "created_at": str(record.get("created_at")),
            }
            self.chroma_collection.add(
                ids=[record["id"]],
                documents=[text],
                metadatas=[metadata],
            )
        except Exception:
            pass


# Shared instance used by agents
hybrid_memory_manager = HybridMemoryManager()
